### ISSUE TITLE
bot upload speed to telegram is too slow even with UK server and token

### ISSUE THREAD

**Issue by sunilroy007** [mvplID/TortoolkitHeroku-DEVILID#2]
bot upload speed to telegram is too slow even with UK server and token

**Comment by aaryanmishra** [comment]
ustatus instadl doesot works

**Comment by sunilroy007** [comment]
> ustatus instadl doesnot works

did you tried rclone does it works?

**Comment by aaryanmishra** [comment]
> > ustatus instadl doesnot works
> 
> did you tried rclone does it works?

yes

**Comment by sunilroy007** [comment]
> > > ustatus instadl doesnot works
> > 
> > 
> > did you tried rclone does it works?
> 
> yes

hmm ok.. this repo is too slow even for torrents and upload speed
